ui <- fluidPage(
  title = "SAPPHIRINE",
  titlePanel(h2(
    "SAPPHIRINE",
    style = "font-weight: bold; margin-bottom: 20px"
  )),
  tabsetPanel(
    tabPanel(
      "Home",
      br(),
      h4(strong("SAPPHIRINE"),
         HTML(paste0(
           "(", strong("S"), "ensor-based ", strong("A"), "nalysis of ",
           strong("P"), "ollution in the ", strong("Phi"), "ladelphia ",
           strong("R"), "egion with ", strong("I"), "nformation on ",
           strong("N"), "eighborhoods and the ", strong("E"), "nvironment)"
         )),
         "is an online web application that integrates social and environmental",
         "geospatial data from the Greater Philadelphia Area.",
         "It provides interactive visualizations to help researchers generate",
         "hypotheses for neighborhood-level health studies in Philadelphia.",
         style = "line-height: 1.5; margin-bottom: 15px"),
      p("SAPPHIRINE consists of the following tabs:"),
      tags$ul(
             tags$li(span("NDVI: ", style = "font-weight: bold; color: red"),
                     "Landsat Normalized Difference Vegetation Index calculated using",
                     "satellite imagery for assessing vegetation greenness"),
             tags$li(span("TRI: ", style = "font-weight: bold; color: maroon"),
                     "Toxic Release Inventory chemicals released into the air"),
             tags$li(span("ADI: ", style = "font-weight: bold; color: olive"),
                     "Area Deprivation Index for assessing socioeconomic",
                     "disadvantage in a region of interest"),
             tags$li(span("SVI: ", style = "font-weight: bold; color: green"),
                     "CDC/ATS Social Vulnerability Index for identifying",
                     "and quantifying communities experiencing social vulnerability"),
             tags$li(span("L&I Violation: ", style = "font-weight: bold; color: navy"),
                     "Asthma-related Licenses and Inspections Code Violations",
                     "in reference to the Philadelphia Building Construction and Occupancy Code",
                     "(Philadelphia County)"),
             tags$li(span("Crime: ", style = "font-weight: bold; color: purple"),
                     "Crime incidents from the Philadelphia Police Department",
                     "(Philadelphia County)"),
             tags$li(span("Traffic: ", style = "font-weight: bold; color: orange"),
                     "Amounts of vehicle traffic that travel the section of roads",
                     "(Philadelphia County)"),
             tags$li(span("EPA Air Quality: ", style = "font-weight: bold; color: brown"),
                     "Air pollutant levels from the EPA's Air Quality System database"),
             tags$li(span("Satellite Air Quality: ", style = "font-weight: bold; color: aqua"),
                     "Satellite-derived air quality data",
                     HTML(paste0("(NO", tags$sub("2"))), "and PM2.5)"),
             style = "line-height: 1.5"
           ),
      p("Data covers the Philadelphia-Camden-Wilmington statistical area,",
        "unless otherwise specified.",
         "To download the data sets for this application, please click",
        a(href = file.path("sapphirine_data.zip"), "[sapphirine_data]",
          target = "_blank"),
        style = "line-height: 1.5"),
      p("We strive to ensure that the data presented is error-free,",
        "but we would not guarantee that it is spatially and temporally accurate."),
      p("The original version of SAPPHRINE is described here:"),
      p("Christie C, Xie S, Diwadkar AR, Greenblatt RE, Rizaldi A, Himes BE.",
        "Consolidated Environmental and Social Data Facilitates Neighborhood-Level",
        "Health Studies in Philadelphia. AMIA Annu Symp Proc. 2022;2021:305-313.",
        a(href = "https://pubmed.ncbi.nlm.nih.gov/35308932/", "PMID: 35308932.",
          target = "_blank")
        ),
      br(),
      h4(strong("Contributors")),
      h4("Jaehyun Joo, Alana Schreibman and Blanca Himes.",
         "Source code is on",
         a(href = "https://github.com/HimesGroup/sapphirine", "GitHub",
           targt = "_blank")),
      br(),
      if (file.exists(file.path("www", "Penn.png"))) {
        ## Do not store Penn logo on GitHub
        tags$img(src = file.path("Penn.png"), width = "15%", height = "15%")
      }
    ),
    ndviUI("NDVI"),
    adiUI("ADI"),
    sviUI("SVI"),
    triUI("TRI"),
    violationUI("Violation"),
    crimeUI("Crime"),
    trafficUI("Traffic"),
    airqualityUI("Airquality"),
    satelliteUI("Satellite")
  )
)
